project:
  type: website
  output-dir: docs

website:
  title: "Diário de Ecologia de paisagens - Anna Luisa"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exercicios/avaliacao_final.qmd
        text: Avaliação final
      - text: Exercícios
        menu:
          - href: exercicios/exercicio_1.qmd
            text: Exercício 1 - O Mosaico no Lance de Vista
          - href: exercicios/exercicio_3.qmd
            text: Exercício 3 - Pacotes R para Ecologia de Paisagens 
          - href: exercicios/exercicio_4.qmd
            text: Exercício 4 - Amostragem de Paisagens com Restrição de Borda — Murici-AL
          - href: exercicios/exercicio_5.qmd
            text: Exercício 5 - Descrevendo uma paisagem


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual